group_content_enabler.config.tracking_enabled:
  type: 'integer'
  label: 'Tracking enabled'

action.configuration.assign_media_to_group:
  type: mapping
  label: 'Assign media to Group'
  mapping:
    group_id:
      type: integer
      label: 'The ID of the group to add media to'

action.configuration.remove_media_from_group:
  type: mapping
  label: 'Remove media from Group'
  mapping:
    group_id:
      type: integer
      label: 'The ID of the group to remove media from'
