groupmedia.settings:
  type: config_object
  label: 'GroupMedia settings'
  mapping:
    tracking_enabled:
      type: boolean
      label: 'Enable tracking'
    bundles:
      type: sequence
      label: 'Media bundles to exclude'
      sequence:
        type: string
        label: 'Media bundle name'

action.configuration.assign_media_to_group:
  type: mapping
  label: 'Assign media to Group'
  mapping:
    group_id:
      type: integer
      label: 'The ID of the group to add media to'

action.configuration.remove_media_from_group:
  type: mapping
  label: 'Remove media from Group'
  mapping:
    group_id:
      type: integer
      label: 'The ID of the group to remove media from'
