<?php

/**
 * @file
 * Allows to associate media content to group.
 */

use Drupal\Component\Utility\Html;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\group\Entity\GroupContentType;
use Drupal\media\MediaTypeInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function groupmedia_media_type_insert(MediaTypeInterface $media_type) {
  \Drupal::service('plugin.manager.group_content_enabler')->clearCachedDefinitions();
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function groupmedia_group_content_insert(EntityInterface $group_content) {
  \Drupal::service('groupmedia.attach_group')->attach($group_content);
}

/**
 * Implements hook_entity_insert().
 */
function groupmedia_entity_update(EntityInterface $entity) {
  \Drupal::service('groupmedia.attach_group')->attach($entity);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function groupmedia_form_media_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\ContentEntityInterface $media */
  $media = $form_state->getFormObject()->getEntity();
  if (!$media->isNew()) {
    $groups = [];
    $group_contents = \Drupal::entityTypeManager()
      ->getStorage('group_content')
      ->loadByEntity($media);
    foreach ($group_contents as $group_content) {
      $group = $group_content->getGroup();
      $groups[] = Link::fromTextAndUrl($group->label(), $group->toUrl('canonical', ['attributes' => ['target' => '_blank']]));
    }
    $form['group_information'] = [
      '#type' => 'details',
      '#title' => t('Groups'),
      '#access' => !empty($groups),
      '#group' => 'advanced',
      '#weight' => 100,
      '#open' => FALSE,
    ];
    $form['group_information']['group_list'] = [
      '#theme' => 'item_list',
      '#items' => $groups,
      '#title' => t('The list of groups media item belongs to:'),
      '#access' => !empty($groups),
    ];
  }
}

/**
 * Implements hook_help().
 */
function groupmedia_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.groupmedia':
      $text = file_get_contents(__DIR__ . '/README.md');
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . Html::escape($text) . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;
}

/**
 * Implements hook_entity_operation().
 */
function groupmedia_entity_operation(EntityInterface $entity) {
  $operations = [];

  if ($entity->getEntityTypeId() == 'group' && \Drupal::moduleHandler()
    ->moduleExists('views')) {
    /** @var \Drupal\group\Entity\GroupInterface $entity */
    if (!$entity->hasPermission('access group_media overview', \Drupal::currentUser())) {
      // Exit early without checking group content plugins.
      return $operations;
    }
    // Get the list of the group_content plugins enabled for this group type.
    $plugin_ids = $entity->getGroupType()
      ->getInstalledContentPlugins()
      ->getInstanceIds();

    // Check if there is any media group_content plugin enabled.
    $has_media = FALSE;
    foreach ($plugin_ids as $plugin_id) {
      if (strpos($plugin_id, 'group_media:') === 0) {
        // We need at least 1 enabled plugin to have the link.
        $has_media = TRUE;
        break;
      }
    }

    /** @var \Drupal\group\Entity\GroupInterface $entity */
    if ($has_media) {
      /** @var \Symfony\Component\Routing\RouterInterface $router */
      $router = \Drupal::service('router.no_access_checks');
      if ($router->getRouteCollection()->get('view.group_media.page_1') !== NULL) {
        $operations['media'] = [
          'title' => t('Media'),
          'weight' => 22,
          'url' => Url::fromRoute('view.group_media.page_1', [
            'group' => $entity->id(),
          ]),
        ];
      }
    }
  }

  return $operations;
}

/**
 * Implements hook_ENTITY_TYPE_create_access().
 */
function groupmedia_group_content_create_access(AccountInterface $account, array $context, $entity_bundle) {

  if (\Drupal::routeMatch()->getRouteName() == 'entity.group_content.group_media_add_page') {
    // Get the group content type from the entity_bundle.
    /** @var \Drupal\group\Entity\GroupContentTypeInterface $group_content_type */
    $group_content_type = GroupContentType::load($entity_bundle);

    // Check if we are dealing with a group_media content plugin.
    $plugin_definition = $group_content_type->getContentPlugin()->getPluginDefinition();
    if ($plugin_definition['id'] == 'group_media' && $plugin_definition['entity_type_id'] == 'media') {
      $media_bundle = $plugin_definition['entity_bundle'];
      $plugin_id = "group_media:$media_bundle";
      $permission = "create $plugin_id entity";

      // Check if user has permission to create this media bundle.
      /** @var \Drupal\group\Entity\GroupInterface $group */
      $group = $context['group'];
      return $group->hasPermission($permission, $account) ? AccessResult::allowed() : AccessResult::neutral();
    }
  }
  return AccessResult::neutral();
}
