<?php

/**
 * @file
 * Install, update and uninstall functions for the groupmedia module.
 */

/**
 * Implements hook_uninstall().
 */
function groupmedia_uninstall() {
  if (\Drupal::moduleHandler()->moduleExists('views')) {
    $view = \Drupal::entityTypeManager()->getStorage('view')->load('group_media');
    if ($view) {
      // Remove the view because it is used only by groupmedia module.
      $view->delete();
    }
  }
}
